// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package entity

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateTodo(ctx context.Context, arg CreateTodoParams) (sql.Result, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	GetOneTodo(ctx context.Context, arg GetOneTodoParams) (Todo, error)
	GetOneUser(ctx context.Context, arg GetOneUserParams) (GetOneUserRow, error)
	ListTodo(ctx context.Context, arg ListTodoParams) ([]Todo, error)
	ListUser(ctx context.Context, arg ListUserParams) ([]ListUserRow, error)
	UpdateTodo(ctx context.Context, arg UpdateTodoParams) (sql.Result, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
