FROM golang:1.23.6-alpine AS builder
WORKDIR /build
COPY . .
RUN apk update && \
apk add tzdata && \
mv -v etc/cfg/conf.dev.json etc/cfg/conf.json && \
go build -o main ./src/cmd/main.go

FROM alpine:3.21 AS runner
WORKDIR /app
COPY --from=builder /build/etc etc/
COPY --from=builder /build/docs docs/
COPY --from=builder /build/main .
EXPOSE 8000
CMD ["./main"]
