name: Todo App
on:
 push:
   # tags:
   #   - v*
   branches:
     - ci/cd
jobs:
  test:
   name: Testing code
   runs-on: ubuntu-latest
   steps:
     - name: clone repo
       uses: actions/checkout@v4
     - name: setup go env
       uses: actions/setup-go@v5
       with:
         go-version: "1.23.6"
     - name: validate go version
       run: go version
     - name: test code
       run: go test -v ./...
  deploy:
   name: deploy to production
   runs-on: ubuntu-latest
   steps:
     - name: clone repo
       uses: actions/checkout@v4
     - run: |
        mkdir -p ${{ secrets.SSH_CONFIG_DIR }};
        chmod -Rv 0600 ${{ secrets.SSH_CONFIG_DIR }};
        echo "${{ secrets.SSH_KEY }}" > ${{ secrets.SSH_CONFIG_DIR }}/${{ secrets.SSH_KEY_FILE }};
        echo "
         Host ${{ secrets.SSH_HOST }}
           HostName ${{ secrets.SSH_HOST }}
           Port ${{ secrets.SSH_PORT }}
           User ${{ secrets.SSH_USER }}
           IdentityFile ${{ secrets.SSH_CONFIG_DIR }}/${{ secrets.SSH_KEY_FILE }}
        " >> ${{ secrets.SSH_CONFIG_DIR }}/${{ secrets.SSH_CONFIG_FILE }};
        ssh -o StrictHostKeyChecking=no -F ${{ secrets.SSH_CONFIG_DIR }}/${{ secrets.SSH_CONFIG_FILE }} ${{ secrets.SSH_HOST }} -- pwd
